HW tests: Fix performance test
ghaf-robot performance test requires the test to be run from the
directory `Robot-Framework/test-suites`. Otherwise, the the test fails
with errors like:

```
FileNotFoundError: [Errno 2] No such file or directory:
'../test-suites/OrinNX1_CPU One thread test.png'
```

This should probably fixed in
https://github.com/tiiuae/ci-test-automation repo, perhaps somewhere in:
```
Robot-Framework/lib/PerformanceDataProcessing.py
```

Signed-off-by: Henri Rosten <henri.rosten@unikie.com>